version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    container_name: es
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200"
    networks:
      - basenet
    restart: always

  kibana:
      image: docker.elastic.co/kibana/kibana:8.2.2
      container_name: kibana
      volumes:
        - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch
      networks:
        - basenet
      restart: always

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    networks:
      - basenet
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
      - "2182:2182"
    restart: always

  kafka:
    image: "bitnami/kafka:latest"
    container_name: kafka_node1
    networks:
      - basenet
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://kafka_node1:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${SERVER_IP}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: ${SERVER_IP}:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms16M"
    restart: always

  mysql8:
      image: mysql:8.0.32-debian
      restart: always
      container_name: mysql8
      environment:
        MYSQL_ROOT_PASSWORD: admin5566
      command:
        --default-authentication-plugin=mysql_native_password
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
        --explicit_defaults_for_timestamp=true
        --lower_case_table_names=1
      ports:
        - 3307:3306
      volumes:
        - ./mysql8/data:/var/lib/mysql
        - ./mysql8/conf:/etc/mysql/conf.d
        - ./mysql8/logs:/logs
      networks:
        - basenet
  redis:
    container_name: redis
    networks:
      - basenet
    image: "bitnami/redis:latest"
    environment:
      - REDIS_PASSWORD=Test@redis
    ports:
      - "6379:6379"
    restart: always

  jaeger:
    image: "jaegertracing/all-in-one:1.34"
    container_name: jaeger
    networks:
      - basenet
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    restart: always

  consul:
    image: "consul:latest"
    container_name: consul
    networks:
      - default
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -bind="0.0.0.0" -client="0.0.0.0"
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    restart: always

  dtm:
    image: "yedf/dtm:sha-8ca8482"
    container_name: dtm
    networks:
      - default
    environment:
      STORE_DRIVER: redis
      STORE_HOST: ${SERVER_IP}
      STORE_USER:
      STORE_PASSWORD: "Test@topgaming"
      STORE_PORT: 6379
      MICRO_SERVICE_DRIVER: "dtm-driver-kratos"
      MICRO_SERVICE_TARGET: "consul://${SERVER_IP}:8500/dtmservice"
      MICRO_SERVICE_END_POINT: "grpc://${SERVER_IP}:36790"
    ports:
      - '36789:36789'
      - '36790:36790'
    restart: always

networks:
  basenet:
    driver: bridge